sudo: required

services:
  - docker

env:
  - CGO_ENABLED=0

language: go

go:
  - "1.12"

install: true

script:
  - ./install_kubebuilder
  - make test
#  - make manifests
  - make manager

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - make docker-build

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master