apiVersion: batch.crossplane.io/v1alpha1
kind: Job
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: job-c
---
apiVersion: batch.crossplane.io/v1alpha1
kind: Job
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: job-b
spec:
# Add fields here
  dependOnJobs:
    - job-c
---
apiVersion: batch.crossplane.io/v1alpha1
kind: Job
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: job-a
spec:
  # Add fields here
  dependOnJobs:
    - job-b
